[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"  # Or "netlify/functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200