[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/functions/:splat"
  status = 200

[[redirects]]
  from = "/api/visits"
  to = "/.netlify/functions/visits"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200